export default {
	products: [
		{
			id: 1,
			name: "Slim Shirt",
			category: "Shirts",
			image: "/images/1.jpg",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 0,
		},
		{
			id: 2,
			name: "Fit Shirt",
			category: "Shirts",
			image: "/images/2.jpg",
			price: 50,
			brand: "Nike",
			rating: 4.2,
			numReviews: 5,
			countInStock: 4,
		},
		{
			id: 3,
			name: "Slim Pants",
			category: "Pants",
			image: "/images/3.jpg",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 8,
			countInStock: 4,
		},
		{
			id: 4,
			name: "Fit Pants",
			category: "Pants",
			image: "/images/4.jpg",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 8,
			countInStock: 2,
		},
	],
};
